spring:
  application:
    name: sustainability-tracker
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sustainability_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: myPassword!
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true

  web:
    error:
      include-message: always
      include-stacktrace: never
      include-binding-errors: never
  jwt:
    secret: thisIsMySecretKeyAndItShouldBeLongEnough123456
    accessTokenExpiration: 604800 # 900 # 15m
    refreshTokenExpiration: 604800 # 7d

server:
  servlet:
    context-path: /api/v1